-- Verified geospatial / Earth-system degree catalogue seed.
-- Official university programme pages researched on 2026-10-08.
insert into public.courses
  (title, slug, degree_type, institution_id, language, duration, website, summary,
   verification_status, confidence, is_demo, last_verified_at)
select v.title, v.slug, v.degree_type, v.institution_id, v.language, v.duration,
       v.website, v.summary, 'auto_discovered', 'medium', false, now()
from (values
  ('Bachelor Geospatial Engineering','eth-zurich-bachelor-geospatial-engineering','Bachelor','97a39c6c-a06b-4a4f-a441-bf422c917569','English','3 years','https://ethz.ch/en/studies/bachelor/bachelors-degree-programmes/architecture-and-civil-engineering/geospatial-engineering.html','Bachelor programme in geospatial engineering covering spatial data, geodesy, measurement technology, cartography, GIS, spatial planning and related engineering fields.'),
  ('Master Geomatics','eth-zurich-master-geomatics','Master','736670db-5621-46a1-b023-f1068e5bab45','English','2 years','https://ethz.ch/en/studies/master/degree-programmes/architecture-and-civil-engineering/geomatics.html','Master programme covering geographic information science, cartography, geodesy, navigation, surveying, geomonitoring, remote sensing and photogrammetry.'),
  ('Bachelor of Science in Earth, Atmospheric and Planetary Sciences','mit-bachelor-earth-atmospheric-planetary-sciences','Bachelor','e141f951-c20a-4495-893b-0d56476095e4','English','4 years','https://eaps.mit.edu/education/undergraduate-program/','MIT Course 12 undergraduate degree covering geophysical sciences and interdisciplinary Earth, atmospheric and planetary science.'),
  ('Master of Science in Earth and Planetary Sciences','mit-sm-earth-planetary-sciences','Master','e141f951-c20a-4495-893b-0d56476095e4','English','Varies','https://eaps.mit.edu/education/graduate-program/','MIT EAPS SM degree in Earth and Planetary Sciences with research-based graduate study.'),
  ('Doctor of Philosophy in Earth, Atmospheric and Planetary Sciences','mit-phd-earth-atmospheric-planetary-sciences','Doctoral','e141f951-c20a-4495-893b-0d56476095e4','English','Typically 5 years','https://catalog.mit.edu/degree-charts/phd-earth-atmospheric-planetary-sciences/','Doctoral programme with fields including geology, geophysics, geobiology, climate and planetary sciences.'),
  ('Master of Science in Atmospheric Science','mit-sm-atmospheric-science','Master','e141f951-c20a-4495-893b-0d56476095e4','English','Varies','https://oge.mit.edu/programs/earth-atmospheric-and-planetary-sciences/','MIT EAPS master degree in atmospheric science.'),
  ('MASt in Earth Sciences','cambridge-mast-earth-sciences','Master','c3933950-a1a7-454d-9b81-94db6cf01fdc','English','9 months','https://www.postgraduate.study.cam.ac.uk/courses/directory/eaesasase','Taught advanced Earth Sciences degree with broad geoscience training and independent research.'),
  ('MPhil in Earth Sciences by Research Thesis','cambridge-mphil-earth-sciences','Master','c3933950-a1a7-454d-9b81-94db6cf01fdc','English','1 year','https://www.esc.cam.ac.uk/postgraduate','Research masters in Earth Sciences offered by Cambridge Earth Sciences.'),
  ('MPhil in Quantitative Climate and Environmental Science','cambridge-mphil-quantitative-climate-environmental-science','Master','c3933950-a1a7-454d-9b81-94db6cf01fdc','English','1 year','https://www.esc.cam.ac.uk/postgraduate','Cambridge masters programme in quantitative climate and environmental science.'),
  ('MPhil in Planetary Sciences and Life','cambridge-mphil-planetary-sciences-life','Master','c3933950-a1a7-454d-9b81-94db6cf01fdc','English','1 year','https://www.esc.cam.ac.uk/postgraduate','Cambridge masters programme focused on planetary sciences and life.'),
  ('DPhil in Earth Sciences','oxford-dphil-earth-sciences','Doctoral','9da82d0e-52a8-4e29-a76e-ad785ce1c887','English','Varies','https://www.ox.ac.uk/admissions/graduate/courses/departments/earth-sciences','Oxford doctoral degree in Earth Sciences spanning geophysics, geodynamics, geodesy, tectonics, climate and related fields.'),
  ('MSc by Research in Earth Sciences','oxford-msc-research-earth-sciences','Master','9da82d0e-52a8-4e29-a76e-ad785ce1c887','English','2-3 years','https://www.ox.ac.uk/admissions/graduate/courses/msc-research-earth-sciences','Research-based Earth Sciences masters with themes including geophysics, geodynamics, geodesy, tectonics, climate and Earth resources.'),
  ('Intelligent Earth','oxford-intelligent-earth','Doctoral','9da82d0e-52a8-4e29-a76e-ad785ce1c887','English','Varies','https://www.ox.ac.uk/admissions/graduate/courses/departments/earth-sciences','UKRI Centre for Doctoral Training in AI for the Environment within Oxford Earth Sciences.'),
  ('Earth and Planetary Science PhD','berkeley-earth-planetary-science-phd','Doctoral','917879f9-37c5-4b69-99c2-069140823bfa','English','Varies','https://eps.berkeley.edu/overview-graduate-program','Berkeley graduate programme leading to a PhD in Earth and Planetary Science.'),
  ('Earth and Planetary Science 5th-Year MA','berkeley-earth-planetary-science-5th-year-ma','Master','917879f9-37c5-4b69-99c2-069140823bfa','English','1 year','https://grad.berkeley.edu/Admissions/Our%20Programs/','Fifth-year Earth and Planetary Science MA for eligible UC Berkeley students.'),
  ('Earth System Science MS','stanford-earth-system-science-ms','Master','3333c759-0f39-4408-ad9e-46a940831c90','English','Varies','https://bulletin.stanford.edu/programs/ESS-MS/program-policies-WgPxM','Stanford master programme studying Earth systems and environmental change across air, water, land and life.'),
  ('Earth Systems MS','stanford-earth-systems-ms','Master','3333c759-0f39-4408-ad9e-46a940831c90','English','1 year','https://bulletin.stanford.edu/programs/EASYS-MS','Stanford interdisciplinary Earth Systems coterminal master programme.'),
  ('Master of Science in Earth and Planetary Science','tokyo-master-earth-planetary-science','Master','7acc8f2d-9bc4-4688-8d34-cc4cf593dd1b','Japanese / English','2 years','https://www.eps.s.u-tokyo.ac.jp/en/graduateschool-overview_en/','University of Tokyo master programme in Earth and Planetary Science with broad specialist and engineering-oriented training.'),
  ('Doctoral Program in Earth and Planetary Science','tokyo-doctoral-earth-planetary-science','Doctoral','7acc8f2d-9bc4-4688-8d34-cc4cf593dd1b','Japanese / English','3 years','https://www.eps.s.u-tokyo.ac.jp/en/graduateschool-overview_en/','University of Tokyo doctoral programme in Earth and Planetary Science focused on original research and advanced specialist training.')
) as v(title,slug,degree_type,institution_id,language,duration,website,summary)
where not exists (select 1 from public.courses c where c.website = v.website and c.is_demo = false);
