/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as CollaborationRouteImport } from './routes/collaboration'
import { Route as MatcherRouteImport } from './routes/matcher'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TopRouteImport } from './routes/top'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as AdminPipelineHealthRouteImport } from './routes/admin.pipeline-health'
import { Route as CountriesIndexRouteImport } from './routes/countries.index'
import { Route as CountriesSlugRouteImport } from './routes/countries.$slug'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as InstitutionsIndexRouteImport } from './routes/institutions.index'
import { Route as InstitutionsSlugRouteImport } from './routes/institutions.$slug'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as JobsSlugRouteImport } from './routes/jobs.$slug'
import { Route as ProgrammesIndexRouteImport } from './routes/programmes.index'
import { Route as ProgrammesSlugRouteImport } from './routes/programmes.$slug'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as PublicationsIndexRouteImport } from './routes/publications.index'
import { Route as PublicationsIdRouteImport } from './routes/publications.$id'
import { Route as ResearchersIndexRouteImport } from './routes/researchers.index'
import { Route as ResearchersSlugRouteImport } from './routes/researchers.$slug'
import { Route as TopicsIndexRouteImport } from './routes/topics.index'
import { Route as TopicsSlugRouteImport } from './routes/topics.$slug'
import { Route as ApiPublicHooksIngestBatchRouteImport } from './routes/api/public/hooks/ingest-batch'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const CollaborationRoute = CollaborationRouteImport.update({
  id: '/collaboration',
  path: '/collaboration',
  getParentRoute: () => rootRouteImport,
} as any)
const MatcherRoute = MatcherRouteImport.update({
  id: '/matcher',
  path: '/matcher',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TopRoute = TopRouteImport.update({
  id: '/top',
  path: '/top',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPipelineHealthRoute = AdminPipelineHealthRouteImport.update({
  id: '/admin/pipeline-health',
  path: '/admin/pipeline-health',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesIndexRoute = CountriesIndexRouteImport.update({
  id: '/countries/',
  path: '/countries/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesSlugRoute = CountriesSlugRouteImport.update({
  id: '/countries/$slug',
  path: '/countries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionsIndexRoute = InstitutionsIndexRouteImport.update({
  id: '/institutions/',
  path: '/institutions/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionsSlugRoute = InstitutionsSlugRouteImport.update({
  id: '/institutions/$slug',
  path: '/institutions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsSlugRoute = JobsSlugRouteImport.update({
  id: '/jobs/$slug',
  path: '/jobs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesIndexRoute = ProgrammesIndexRouteImport.update({
  id: '/programmes/',
  path: '/programmes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesSlugRoute = ProgrammesSlugRouteImport.update({
  id: '/programmes/$slug',
  path: '/programmes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsIndexRoute = PublicationsIndexRouteImport.update({
  id: '/publications/',
  path: '/publications/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsIdRoute = PublicationsIdRouteImport.update({
  id: '/publications/$id',
  path: '/publications/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchersIndexRoute = ResearchersIndexRouteImport.update({
  id: '/researchers/',
  path: '/researchers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchersSlugRoute = ResearchersSlugRouteImport.update({
  id: '/researchers/$slug',
  path: '/researchers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsIndexRoute = TopicsIndexRouteImport.update({
  id: '/topics/',
  path: '/topics/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsSlugRoute = TopicsSlugRouteImport.update({
  id: '/topics/$slug',
  path: '/topics/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksIngestBatchRoute =
  ApiPublicHooksIngestBatchRouteImport.update({
    id: '/api/public/hooks/ingest-batch',
    path: '/api/public/hooks/ingest-batch',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/collaboration': typeof CollaborationRoute
  '/matcher': typeof MatcherRoute
  '/methodology': typeof MethodologyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/top': typeof TopRoute
  '/trends': typeof TrendsRoute
  '/admin/pipeline-health': typeof AdminPipelineHealthRoute
  '/countries/$slug': typeof CountriesSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/institutions/$slug': typeof InstitutionsSlugRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/programmes/$slug': typeof ProgrammesSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/publications/$id': typeof PublicationsIdRoute
  '/researchers/$slug': typeof ResearchersSlugRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/countries/': typeof CountriesIndexRoute
  '/events/': typeof EventsIndexRoute
  '/institutions/': typeof InstitutionsIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/programmes/': typeof ProgrammesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/publications/': typeof PublicationsIndexRoute
  '/researchers/': typeof ResearchersIndexRoute
  '/topics/': typeof TopicsIndexRoute
  '/api/public/hooks/ingest-batch': typeof ApiPublicHooksIngestBatchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/collaboration': typeof CollaborationRoute
  '/matcher': typeof MatcherRoute
  '/methodology': typeof MethodologyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/top': typeof TopRoute
  '/trends': typeof TrendsRoute
  '/admin/pipeline-health': typeof AdminPipelineHealthRoute
  '/countries/$slug': typeof CountriesSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/institutions/$slug': typeof InstitutionsSlugRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/programmes/$slug': typeof ProgrammesSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/publications/$id': typeof PublicationsIdRoute
  '/researchers/$slug': typeof ResearchersSlugRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/countries': typeof CountriesIndexRoute
  '/events': typeof EventsIndexRoute
  '/institutions': typeof InstitutionsIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/programmes': typeof ProgrammesIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/publications': typeof PublicationsIndexRoute
  '/researchers': typeof ResearchersIndexRoute
  '/topics': typeof TopicsIndexRoute
  '/api/public/hooks/ingest-batch': typeof ApiPublicHooksIngestBatchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/collaboration': typeof CollaborationRoute
  '/matcher': typeof MatcherRoute
  '/methodology': typeof MethodologyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/top': typeof TopRoute
  '/trends': typeof TrendsRoute
  '/admin/pipeline-health': typeof AdminPipelineHealthRoute
  '/countries/$slug': typeof CountriesSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/institutions/$slug': typeof InstitutionsSlugRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/programmes/$slug': typeof ProgrammesSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/publications/$id': typeof PublicationsIdRoute
  '/researchers/$slug': typeof ResearchersSlugRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/countries/': typeof CountriesIndexRoute
  '/events/': typeof EventsIndexRoute
  '/institutions/': typeof InstitutionsIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/programmes/': typeof ProgrammesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/publications/': typeof PublicationsIndexRoute
  '/researchers/': typeof ResearchersIndexRoute
  '/topics/': typeof TopicsIndexRoute
  '/api/public/hooks/ingest-batch': typeof ApiPublicHooksIngestBatchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atlas'
    | '/collaboration'
    | '/matcher'
    | '/methodology'
    | '/sitemap.xml'
    | '/top'
    | '/trends'
    | '/admin/pipeline-health'
    | '/countries/$slug'
    | '/events/$slug'
    | '/institutions/$slug'
    | '/jobs/$slug'
    | '/programmes/$slug'
    | '/projects/$slug'
    | '/publications/$id'
    | '/researchers/$slug'
    | '/topics/$slug'
    | '/countries/'
    | '/events/'
    | '/institutions/'
    | '/jobs/'
    | '/programmes/'
    | '/projects/'
    | '/publications/'
    | '/researchers/'
    | '/topics/'
    | '/api/public/hooks/ingest-batch'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atlas'
    | '/collaboration'
    | '/matcher'
    | '/methodology'
    | '/sitemap.xml'
    | '/top'
    | '/trends'
    | '/admin/pipeline-health'
    | '/countries/$slug'
    | '/events/$slug'
    | '/institutions/$slug'
    | '/jobs/$slug'
    | '/programmes/$slug'
    | '/projects/$slug'
    | '/publications/$id'
    | '/researchers/$slug'
    | '/topics/$slug'
    | '/countries'
    | '/events'
    | '/institutions'
    | '/jobs'
    | '/programmes'
    | '/projects'
    | '/publications'
    | '/researchers'
    | '/topics'
    | '/api/public/hooks/ingest-batch'
  id:
    | '__root__'
    | '/'
    | '/atlas'
    | '/collaboration'
    | '/matcher'
    | '/methodology'
    | '/sitemap.xml'
    | '/top'
    | '/trends'
    | '/admin/pipeline-health'
    | '/countries/$slug'
    | '/events/$slug'
    | '/institutions/$slug'
    | '/jobs/$slug'
    | '/programmes/$slug'
    | '/projects/$slug'
    | '/publications/$id'
    | '/researchers/$slug'
    | '/topics/$slug'
    | '/countries/'
    | '/events/'
    | '/institutions/'
    | '/jobs/'
    | '/programmes/'
    | '/projects/'
    | '/publications/'
    | '/researchers/'
    | '/topics/'
    | '/api/public/hooks/ingest-batch'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtlasRoute: typeof AtlasRoute
  CollaborationRoute: typeof CollaborationRoute
  MatcherRoute: typeof MatcherRoute
  MethodologyRoute: typeof MethodologyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TopRoute: typeof TopRoute
  TrendsRoute: typeof TrendsRoute
  AdminPipelineHealthRoute: typeof AdminPipelineHealthRoute
  CountriesSlugRoute: typeof CountriesSlugRoute
  EventsSlugRoute: typeof EventsSlugRoute
  InstitutionsSlugRoute: typeof InstitutionsSlugRoute
  JobsSlugRoute: typeof JobsSlugRoute
  ProgrammesSlugRoute: typeof ProgrammesSlugRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  PublicationsIdRoute: typeof PublicationsIdRoute
  ResearchersSlugRoute: typeof ResearchersSlugRoute
  TopicsSlugRoute: typeof TopicsSlugRoute
  CountriesIndexRoute: typeof CountriesIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  InstitutionsIndexRoute: typeof InstitutionsIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
  ProgrammesIndexRoute: typeof ProgrammesIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  PublicationsIndexRoute: typeof PublicationsIndexRoute
  ResearchersIndexRoute: typeof ResearchersIndexRoute
  TopicsIndexRoute: typeof TopicsIndexRoute
  ApiPublicHooksIngestBatchRoute: typeof ApiPublicHooksIngestBatchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collaboration': {
      id: '/collaboration'
      path: '/collaboration'
      fullPath: '/collaboration'
      preLoaderRoute: typeof CollaborationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matcher': {
      id: '/matcher'
      path: '/matcher'
      fullPath: '/matcher'
      preLoaderRoute: typeof MatcherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top': {
      id: '/top'
      path: '/top'
      fullPath: '/top'
      preLoaderRoute: typeof TopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pipeline-health': {
      id: '/admin/pipeline-health'
      path: '/admin/pipeline-health'
      fullPath: '/admin/pipeline-health'
      preLoaderRoute: typeof AdminPipelineHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/': {
      id: '/countries/'
      path: '/countries'
      fullPath: '/countries/'
      preLoaderRoute: typeof CountriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/$slug': {
      id: '/countries/$slug'
      path: '/countries/$slug'
      fullPath: '/countries/$slug'
      preLoaderRoute: typeof CountriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutions/': {
      id: '/institutions/'
      path: '/institutions'
      fullPath: '/institutions/'
      preLoaderRoute: typeof InstitutionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutions/$slug': {
      id: '/institutions/$slug'
      path: '/institutions/$slug'
      fullPath: '/institutions/$slug'
      preLoaderRoute: typeof InstitutionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$slug': {
      id: '/jobs/$slug'
      path: '/jobs/$slug'
      fullPath: '/jobs/$slug'
      preLoaderRoute: typeof JobsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/': {
      id: '/programmes/'
      path: '/programmes'
      fullPath: '/programmes/'
      preLoaderRoute: typeof ProgrammesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/$slug': {
      id: '/programmes/$slug'
      path: '/programmes/$slug'
      fullPath: '/programmes/$slug'
      preLoaderRoute: typeof ProgrammesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications/': {
      id: '/publications/'
      path: '/publications'
      fullPath: '/publications/'
      preLoaderRoute: typeof PublicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications/$id': {
      id: '/publications/$id'
      path: '/publications/$id'
      fullPath: '/publications/$id'
      preLoaderRoute: typeof PublicationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/researchers/': {
      id: '/researchers/'
      path: '/researchers'
      fullPath: '/researchers/'
      preLoaderRoute: typeof ResearchersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/researchers/$slug': {
      id: '/researchers/$slug'
      path: '/researchers/$slug'
      fullPath: '/researchers/$slug'
      preLoaderRoute: typeof ResearchersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/': {
      id: '/topics/'
      path: '/topics'
      fullPath: '/topics/'
      preLoaderRoute: typeof TopicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$slug': {
      id: '/topics/$slug'
      path: '/topics/$slug'
      fullPath: '/topics/$slug'
      preLoaderRoute: typeof TopicsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ingest-batch': {
      id: '/api/public/hooks/ingest-batch'
      path: '/api/public/hooks/ingest-batch'
      fullPath: '/api/public/hooks/ingest-batch'
      preLoaderRoute: typeof ApiPublicHooksIngestBatchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtlasRoute: AtlasRoute,
  CollaborationRoute: CollaborationRoute,
  MatcherRoute: MatcherRoute,
  MethodologyRoute: MethodologyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TopRoute: TopRoute,
  TrendsRoute: TrendsRoute,
  AdminPipelineHealthRoute: AdminPipelineHealthRoute,
  CountriesSlugRoute: CountriesSlugRoute,
  EventsSlugRoute: EventsSlugRoute,
  InstitutionsSlugRoute: InstitutionsSlugRoute,
  JobsSlugRoute: JobsSlugRoute,
  ProgrammesSlugRoute: ProgrammesSlugRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  PublicationsIdRoute: PublicationsIdRoute,
  ResearchersSlugRoute: ResearchersSlugRoute,
  TopicsSlugRoute: TopicsSlugRoute,
  CountriesIndexRoute: CountriesIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  InstitutionsIndexRoute: InstitutionsIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
  ProgrammesIndexRoute: ProgrammesIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  PublicationsIndexRoute: PublicationsIndexRoute,
  ResearchersIndexRoute: ResearchersIndexRoute,
  TopicsIndexRoute: TopicsIndexRoute,
  ApiPublicHooksIngestBatchRoute: ApiPublicHooksIngestBatchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
