CREATE SCHEMA IF NOT EXISTS extensions;
DO $$
BEGIN
  BEGIN
    ALTER EXTENSION pg_net SET SCHEMA extensions;
  EXCEPTION WHEN OTHERS THEN NULL;
  END;
  BEGIN
    ALTER EXTENSION pg_cron SET SCHEMA extensions;
  EXCEPTION WHEN OTHERS THEN NULL;
  END;
END $$;